import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import { ToastContainer } from "@/components/common/toast/Toast";
import { routing } from "@/i18n/routing";
import { Providers } from "@/providers/providers";

import "./../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as "en" | "ru")) {
    notFound();
  }

  const messages = await getMessages({ locale });

  return (
    <html lang={locale} data-theme="default">
      <body
        className={`antialiased relative w-full min-h-screen`}
        id="modal-container"
      >
        <Providers>
          <NextIntlClientProvider messages={messages}>
            {children}
            <ToastContainer />
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
